version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: climb-rails
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - climb-rails-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - climb-rails-redis:/var/lib/redis/data

  climb-rails:
    build: 
      context: ./backend
      dockerfile: ./dockerfiles/Dockerfile.climbrails
    volumes:
      - ./backend:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  climb-react:
    build: 
      context: ./frontend
      dockerfile: dockerfiles/Dockerfile.climbreact
    depends_on:
      - climb-rails
    command: npm start
    volumes:
      - ./frontend/:/usr/src/climb-react
      - ./frontend/node_modules:/usr/src/climb-react/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true

  sidekiq:
    build:
      context: ./backend
      dockerfile: ./dockerfiles/Dockerfile.climbrails
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./backend/dockerfiles/Dockerfile.nginx
    links:
      - climb-rails
    ports:
      - '8020:8020'

volumes:
  climb-rails-postgres:
  climb-rails-redis: