FROM ruby:3.2.2 AS climb-rails-development

# Default directory
ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

# Install gems
WORKDIR $INSTALL_PATH
COPY . .
RUN gem install rails bundler
RUN bundle install

# Start server
CMD bundle exec unicorn -c config/unicorn.rb